### ISSUE TITLE
Open source license is missing like MIT or APACHE 2.0 

### ISSUE THREAD

**Issue by harshit-jaiswal** [furofo/TabGroupExtension#5]
Dear all,

Your extension is very nice and I really liked it.

I would like to share this with my colleagues and use inside the company.
By which you will get many users and feedback for further development.

But due to missing license type we are not allowed to use it for commercial propose.
It would be really nice if you can include MIT or APACHE 2.0 license in your extension.

Best Regards,
Harshit Jaiswal

**Comment by furofo** [comment]
I am glad you like it, I believe I added the MIT license to it so feel free to use it!

**Comment by furofo** [comment]
Hey Harshit,

I am glad you liked my extension. It started out as a personal problem for
me and I decided to make it public and I update it whenever I get the
chance/feedback from users.  I am sure you saw already but I updated the
license on the application and have been updating it to typescript. Not
sure when you forked it but if wasn't working before should be now. I am
working on setting up a CI/CD pipeline for it and tests using Jest. Also
want to add a few features to it once I get that done.

Also if you know anyone who would be open to hiring someone as a dev who
lives in Helsinki could you let me know?

Thanks for your time!
Christian Malpass
